# Generated by Django 3.2.2 on 2021-07-19 05:08

from django.db import migrations, models
import django.db.models.deletion
import faceRecoApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSingup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('user_email', models.EmailField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('group_name', models.CharField(max_length=50, null=True)),
                ('employee_id', models.CharField(max_length=500, null=True)),
                ('imagePath', models.ImageField(null=True, upload_to=faceRecoApp.models.getDisplayImagePath)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_time', models.DateTimeField(auto_now_add=True)),
                ('imagePath', models.ImageField(null=True, upload_to=faceRecoApp.models.getDisplayEmployeeAttendanceImagePath)),
                ('empMessage', models.TextField(max_length=5000, null=True)),
                ('empAddress', models.TextField(max_length=5000, null=True)),
                ('empDeviceInfo', models.CharField(max_length=200, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeAttendance', to='faceRecoApp.employeesingup')),
            ],
        ),
    ]
