# Generated by Django 3.2.2 on 2021-07-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendance',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
