# Generated by Django 3.2.2 on 2021-07-20 09:40

from django.db import migrations, models
import faceRecoApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecoApp', '0003_auto_20210719_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesingup',
            name='imagePath',
            field=models.FileField(null=True, upload_to=faceRecoApp.models.getDisplayImagePath),
        ),
    ]
