# Generated by Django 3.2.2 on 2021-07-21 09:29

from django.db import migrations, models
import faceRecoApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('faceRecoApp', '0004_alter_employeesingup_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='imagePath',
            field=models.FileField(null=True, upload_to=faceRecoApp.models.getDisplayEmployeeAttendanceImagePath),
        ),
    ]
